version: '3'
services:
  saltmaster-local:
    container_name: saltmaster-local
    build:
      context: .
      dockerfile: ./docker/dockerfile-saltmaster
    ports:
      - 4505:4505
      - 4506:4506
      - 3333:3333
    volumes:
    - ./srv/:/srv/
    - ./conf/master:/etc/salt/master
    - ../saltgui:/saltgui
    entrypoint: /usr/bin/supervisord

  saltminion-ubuntu:
    container_name: saltminion-ubuntu-local
    build:
      context: .
      dockerfile: ./docker/dockerfile-saltminion-ubuntu

    depends_on:
       - saltmaster-local
    restart: on-failure
    command: /usr/bin/salt-minion
